/**
 * This file was auto-generated by openapi-to-ts. Do not change it manually!
 */

export interface ICreatureArrayStrFilterSchema {
  field: CreatureArrayStrFilterEnum;
  comparator: ArrayFilterComparators;
  value?: Partial<string> & Partial<number>;
}

export interface ICreatureFiltersSchema {
  filters: Array<
    | ICreatureIntFilterSchema
    | ICreatureStrFilterSchema
    | ICreatureArrayStrFilterSchema
  >;
}

export interface ICreatureIntFilterSchema {
  field: CreatureIntFilterEnum;
  comparator: NumericFilterComparators;
  value?: Partial<number> & Partial<number>;
}

export interface ICreatureModel {
  id: number;
  name: string;
  slug: string;
  description?: string;
  battle_sprite: string;
  health: number;
  attack: number;
  intelligence: number;
  defense: number;
  speed: number;
  klass: IKlassModel;
  race: IRaceModel;
  sources: Array<ISourceModel>;
  trait: ITraitModel;
  created_at: string;
  updated_at: string;
}

export interface ICreatureSortingRequestSchema {
  by?: CreatureSortingEnum;
  direction?: SortDirections;
}

export interface ICreatureSortingResponseSchema {
  by: CreatureSortingEnum;
  direction: SortDirections;
}

export interface ICreatureStrFilterSchema {
  field: CreatureStrFilterEnum;
  comparator: StringFilterComparators;
  value?: string;
}

export interface ICreaturesGetSchema {
  data: ICreatureModel;
}

export interface ICreaturesIndexSchema {
  data: Array<ICreatureModel>;
  pagination: IPaginationResponseSchema;
  sorting: ICreatureSortingResponseSchema;
}

export interface ICreaturesSearchRequest {
  filter: ICreatureFiltersSchema;
  pagination?: IPaginationRequestSchema;
  sorting?: ICreatureSortingRequestSchema;
}

export interface ICreaturesSearchSchema {
  data: Array<ICreatureModel>;
  filter: ICreatureFiltersSchema;
  pagination: IPaginationResponseSchema;
  sorting: ICreatureSortingResponseSchema;
}

export interface IHTTPValidationError {
  detail?: Array<IValidationError>;
}

export interface IHealthCheckSchema {
  healthcheck: boolean;
}

export interface IKlassFiltersSchema {
  filters: Array<IKlassIntFilterSchema | IKlassStrFilterSchema>;
}

export interface IKlassIntFilterSchema {
  field: KlassIntFilterEnum;
  comparator: NumericFilterComparators;
  value?: Partial<number> & Partial<number>;
}

export interface IKlassModel {
  id: number;
  name: string;
  slug: string;
  description?: string;
  color: string;
  icon: string;
  created_at: string;
  updated_at: string;
}

export interface IKlassSortingRequestSchema {
  by?: KlassSortingEnum;
  direction?: SortDirections;
}

export interface IKlassSortingResponseSchema {
  by: KlassSortingEnum;
  direction: SortDirections;
}

export interface IKlassStrFilterSchema {
  field: KlassStrFilterEnum;
  comparator: StringFilterComparators;
  value?: string;
}

export interface IKlassesGetSchema {
  data: IKlassModel;
}

export interface IKlassesIndexSchema {
  data: Array<IKlassModel>;
  pagination: IPaginationResponseSchema;
  sorting: IKlassSortingResponseSchema;
}

export interface IKlassesSearchRequest {
  filter: IKlassFiltersSchema;
  pagination?: IPaginationRequestSchema;
  sorting?: IKlassSortingRequestSchema;
}

export interface IKlassesSearchSchema {
  data: Array<IKlassModel>;
  filter: IKlassFiltersSchema;
  pagination: IPaginationResponseSchema;
  sorting: IKlassSortingResponseSchema;
}

export interface IPaginationRequestSchema {
  page?: number;
  size?: number;
}

export interface IPaginationResponseSchema {
  page: number;
  size: number;
  count: number;
}

export interface IRaceFiltersSchema {
  filters: Array<IRaceIntFilterSchema | IRaceStrFilterSchema>;
}

export interface IRaceIntFilterSchema {
  field: RaceIntFilterEnum;
  comparator: NumericFilterComparators;
  value?: Partial<number> & Partial<number>;
}

export interface IRaceModel {
  id: number;
  name: string;
  slug: string;
  description?: string;
  default_klass: IKlassModel;
  created_at: string;
  updated_at: string;
}

export interface IRaceSortingRequestSchema {
  by?: RaceSortingEnum;
  direction?: SortDirections;
}

export interface IRaceSortingResponseSchema {
  by: RaceSortingEnum;
  direction: SortDirections;
}

export interface IRaceStrFilterSchema {
  field: RaceStrFilterEnum;
  comparator: StringFilterComparators;
  value?: string;
}

export interface IRacesGetSchema {
  data: IRaceModel;
}

export interface IRacesIndexSchema {
  data: Array<IRaceModel>;
  pagination: IPaginationResponseSchema;
  sorting: IRaceSortingResponseSchema;
}

export interface IRacesSearchRequest {
  filter: IRaceFiltersSchema;
  pagination?: IPaginationRequestSchema;
  sorting?: IRaceSortingRequestSchema;
}

export interface IRacesSearchSchema {
  data: Array<IRaceModel>;
  filter: IRaceFiltersSchema;
  pagination: IPaginationResponseSchema;
  sorting: IRaceSortingResponseSchema;
}

export interface IRootSchema {
  data: IHealthCheckSchema;
}

export interface ISourceFiltersSchema {
  filters: Array<ISourceIntFilterSchema | ISourceStrFilterSchema>;
}

export interface ISourceIntFilterSchema {
  field: SourceIntFilterEnum;
  comparator: NumericFilterComparators;
  value?: Partial<number> & Partial<number>;
}

export interface ISourceModel {
  id: number;
  name: string;
  slug: string;
  description?: string;
  created_at: string;
  updated_at: string;
}

export interface ISourceSortingRequestSchema {
  by?: SourceSortingEnum;
  direction?: SortDirections;
}

export interface ISourceSortingResponseSchema {
  by: SourceSortingEnum;
  direction: SortDirections;
}

export interface ISourceStrFilterSchema {
  field: SourceStrFilterEnum;
  comparator: StringFilterComparators;
  value?: string;
}

export interface ISourcesGetSchema {
  data: ISourceModel;
}

export interface ISourcesIndexSchema {
  data: Array<ISourceModel>;
  pagination: IPaginationResponseSchema;
  sorting: ISourceSortingResponseSchema;
}

export interface ISourcesSearchRequest {
  filter: ISourceFiltersSchema;
  pagination?: IPaginationRequestSchema;
  sorting?: ISourceSortingRequestSchema;
}

export interface ISourcesSearchSchema {
  data: Array<ISourceModel>;
  filter: ISourceFiltersSchema;
  pagination: IPaginationResponseSchema;
  sorting: ISourceSortingResponseSchema;
}

export interface ISpellArrayStrFilterSchema {
  field: SpellArrayStrFilterEnum;
  comparator: ArrayFilterComparators;
  value?: Partial<string> & Partial<number>;
}

export interface ISpellFiltersSchema {
  filters: Array<
    ISpellIntFilterSchema | ISpellStrFilterSchema | ISpellArrayStrFilterSchema
  >;
}

export interface ISpellIntFilterSchema {
  field: SpellIntFilterEnum;
  comparator: NumericFilterComparators;
  value?: Partial<number> & Partial<number>;
}

export interface ISpellModel {
  id: number;
  name: string;
  slug: string;
  description?: string;
  charges: number;
  klass: IKlassModel;
  source: ISourceModel;
  tags: Array<string>;
  created_at: string;
  updated_at: string;
}

export interface ISpellSortingRequestSchema {
  by?: SpellSortingEnum;
  direction?: SortDirections;
}

export interface ISpellSortingResponseSchema {
  by: SpellSortingEnum;
  direction: SortDirections;
}

export interface ISpellStrFilterSchema {
  field: SpellStrFilterEnum;
  comparator: StringFilterComparators;
  value?: string;
}

export interface ISpellsGetSchema {
  data: ISpellModel;
}

export interface ISpellsIndexSchema {
  data: Array<ISpellModel>;
  pagination: IPaginationResponseSchema;
  sorting: ISpellSortingResponseSchema;
}

export interface ISpellsSearchRequest {
  filter: ISpellFiltersSchema;
  pagination?: IPaginationRequestSchema;
  sorting?: ISpellSortingRequestSchema;
}

export interface ISpellsSearchSchema {
  data: Array<ISpellModel>;
  filter: ISpellFiltersSchema;
  pagination: IPaginationResponseSchema;
  sorting: ISpellSortingResponseSchema;
}

export interface IStatusEffectFiltersSchema {
  filters: Array<IStatusEffectIntFilterSchema | IStatusEffectStrFilterSchema>;
}

export interface IStatusEffectIntFilterSchema {
  field: StatusEffectIntFilterEnum;
  comparator: NumericFilterComparators;
  value?: Partial<number> & Partial<number>;
}

export interface IStatusEffectModel {
  id: number;
  name: string;
  slug: string;
  description?: string;
  category: StatusEffectCategoriesEnum;
  icon: string;
  turns?: number;
  leave_chance?: number;
  max_stacks: number;
  created_at: string;
  updated_at: string;
}

export interface IStatusEffectStrFilterSchema {
  field: StatusEffectStrFilterEnum;
  comparator: StringFilterComparators;
  value?: string;
}

export interface IStatusEffectsGetSchema {
  data: IStatusEffectModel;
}

export interface IStatusEffectsIndexSchema {
  data: Array<IStatusEffectModel>;
  pagination: IPaginationResponseSchema;
  sorting: IStatusEffetSortingResponseSchema;
}

export interface IStatusEffectsSearchRequest {
  filter: IStatusEffectFiltersSchema;
  pagination?: IPaginationRequestSchema;
  sorting?: IStatusEffetSortingRequestSchema;
}

export interface IStatusEffectsSearchSchema {
  data: Array<IStatusEffectModel>;
  filter: IStatusEffectFiltersSchema;
  pagination: IPaginationResponseSchema;
  sorting: IStatusEffetSortingResponseSchema;
}

export interface IStatusEffetSortingRequestSchema {
  by?: StatusEffetSortingEnum;
  direction?: SortDirections;
}

export interface IStatusEffetSortingResponseSchema {
  by: StatusEffetSortingEnum;
  direction: SortDirections;
}

export interface ITraitArrayStrFilterSchema {
  field: TraitArrayStrFilterEnum;
  comparator: ArrayFilterComparators;
  value?: Partial<string> & Partial<number>;
}

export interface ITraitFiltersSchema {
  filters: Array<
    ITraitIntFilterSchema | ITraitStrFilterSchema | ITraitArrayStrFilterSchema
  >;
}

export interface ITraitIntFilterSchema {
  field: TraitIntFilterEnum;
  comparator: NumericFilterComparators;
  value?: Partial<number> & Partial<number>;
}

export interface ITraitModel {
  id: number;
  name: string;
  slug: string;
  description?: string;
  material_name?: string;
  tags: Array<string>;
  created_at: string;
  updated_at: string;
}

export interface ITraitSortingRequestSchema {
  by?: TraitSortingEnum;
  direction?: SortDirections;
}

export interface ITraitSortingResponseSchema {
  by: TraitSortingEnum;
  direction: SortDirections;
}

export interface ITraitStrFilterSchema {
  field: TraitStrFilterEnum;
  comparator: StringFilterComparators;
  value?: string;
}

export interface ITraitsGetSchema {
  data: ITraitModel;
}

export interface ITraitsIndexSchema {
  data: Array<ITraitModel>;
  pagination: IPaginationResponseSchema;
  sorting: ITraitSortingResponseSchema;
}

export interface ITraitsSearchRequest {
  filter: ITraitFiltersSchema;
  pagination?: IPaginationRequestSchema;
  sorting?: ITraitSortingRequestSchema;
}

export interface ITraitsSearchSchema {
  data: Array<ITraitModel>;
  filter: ITraitFiltersSchema;
  pagination: IPaginationResponseSchema;
  sorting: ITraitSortingResponseSchema;
}

export interface IValidationError {
  loc: Array<string>;
  msg: string;
  type: string;
}

/**
 * An enumeration.
 */
export type ArrayFilterComparators =
  | "&&"
  | "@>"
  | "<@"
  | "=="
  | "!="
  | "is_null"
  | "is_not_null";

/**
 * An enumeration.
 */
export type CreatureArrayStrFilterEnum = "trait_tags";

/**
 * An enumeration.
 */
export type CreatureIntFilterEnum =
  | "id"
  | "health"
  | "attack"
  | "intelligence"
  | "defense"
  | "speed"
  | "klass_id"
  | "race_id"
  | "trait_id";

/**
 * An enumeration.
 */
export type CreatureSortingEnum =
  | "id"
  | "name"
  | "health"
  | "attack"
  | "intelligence"
  | "defense"
  | "speed"
  | "klass_id"
  | "klass_name"
  | "race_id"
  | "race_name"
  | "trait_id"
  | "trait_name"
  | "trait_tags";

/**
 * An enumeration.
 */
export type CreatureStrFilterEnum =
  | "name"
  | "klass_name"
  | "race_name"
  | "trait_name";

/**
 * An enumeration.
 */
export type KlassIntFilterEnum = "id";

/**
 * An enumeration.
 */
export type KlassSortingEnum = "id" | "name";

/**
 * An enumeration.
 */
export type KlassStrFilterEnum = "name";

/**
 * An enumeration.
 */
export type NumericFilterComparators =
  | "=="
  | "!="
  | ">"
  | ">="
  | "<"
  | "<="
  | "is_null"
  | "is_not_null";

/**
 * An enumeration.
 */
export type RaceIntFilterEnum = "id" | "default_klass_id";

/**
 * An enumeration.
 */
export type RaceSortingEnum =
  | "id"
  | "name"
  | "default_klass_id"
  | "default_klass_name";

/**
 * An enumeration.
 */
export type RaceStrFilterEnum = "name" | "default_klass_name";

/**
 * An enumeration.
 */
export type SortDirections = "asc" | "desc";

/**
 * An enumeration.
 */
export type SourceIntFilterEnum = "id";

/**
 * An enumeration.
 */
export type SourceSortingEnum = "id" | "name";

/**
 * An enumeration.
 */
export type SourceStrFilterEnum = "name";

/**
 * An enumeration.
 */
export type SpellArrayStrFilterEnum = "tags";

/**
 * An enumeration.
 */
export type SpellIntFilterEnum = "id" | "charges" | "klass_id" | "source_id";

/**
 * An enumeration.
 */
export type SpellSortingEnum =
  | "id"
  | "name"
  | "charges"
  | "klass_id"
  | "klass_name"
  | "source_id"
  | "source_name"
  | "tags";

/**
 * An enumeration.
 */
export type SpellStrFilterEnum = "name" | "klass_name" | "source_name";

/**
 * An enumeration.
 */
export type StatusEffectCategoriesEnum = "buff" | "debuff" | "minion";

/**
 * An enumeration.
 */
export type StatusEffectIntFilterEnum = "id" | "leave_chance" | "max_stacks";

/**
 * An enumeration.
 */
export type StatusEffectStrFilterEnum = "name" | "category" | "turns";

/**
 * An enumeration.
 */
export type StatusEffetSortingEnum =
  | "id"
  | "name"
  | "category"
  | "turns"
  | "leave_chance"
  | "max_stacks";

/**
 * An enumeration.
 */
export type StringFilterComparators =
  | "=="
  | "!="
  | "is_null"
  | "is_not_null"
  | "like"
  | "ilike";

/**
 * An enumeration.
 */
export type TraitArrayStrFilterEnum = "tags";

/**
 * An enumeration.
 */
export type TraitIntFilterEnum = "id";

/**
 * An enumeration.
 */
export type TraitSortingEnum = "id" | "name" | "material_name" | "tags";

/**
 * An enumeration.
 */
export type TraitStrFilterEnum = "name" | "material_name";
