name: siralim-ultimate-ui-ci-main-branch
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'rovermicrover/siralim-ultimate-dev'
      - uses: actions/checkout@v2
        with:
          path: ./siralim-ultimate-api
      - uses: actions/checkout@v2
        with:
          repository: 'rovermicrover/siralim-ultimate-nginx'
          path: ./siralim-ultimate-nginx
      - uses: actions/checkout@v2
        with:
          repository: 'rovermicrover/siralim-ultimate-ui'
          path: ./siralim-ultimate-ui
      - uses: actions/checkout@v2
        with:
          repository: 'rovermicrover/siralim-ultimate-ocr'
          path: ./siralim-ultimate-ocr
      - name: Build and run checks
        run: ./commands/ui/ci
  heroku:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push --app ${{ secrets.HEROKU_APP_NAME }} web 
      - name: Release app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release --app ${{ secrets.HEROKU_APP_NAME }} web
            